### PR TITLE
Expose requester ids on authentication service

### PR DESCRIPTION
**Pull request by MKodde**
The state handle stores these ids in its value store. The service can be
used to retrieve them in the application.

This PR relates to: 
https://github.com/OpenConext/Stepup-Azure-MFA/pull/24
https://github.com/OpenConext/Stepup-saml-bundle/pull/97

### CODE REVIEW

**Review by pablothedude — APPROVED** [review]
Missing tests, but further looking good

**Comment by MKodde** [comment]
You're right, added two test sets.

**Comment by pablothedude** [comment]
The change itself looks good but I was wondering what we need to do with the change of the StateHandlerInterface in other GSSP's?

**Review by pablothedude — APPROVED** [review]

**Comment by MKodde** [comment]
Good point, I'm adding a warning to the CHANGLOG.md to instruct updaters to implement these methods in their own implementations

**Pull request merged**
